### ISSUE TITLE
Add stateless session handling

### ISSUE THREAD

**Issue by JacobReynolds** [JacobReynolds/ssrfDetector#5]
Current sessions are only stored in the Node server.  This means load balancing has to be sticky, and upgrades will force users to sign in again.

**Comment by shark0der** [comment]
Also the session secret ("supernova") is hard-coded. This should be loaded from the environment.

**Comment by JacobReynolds** [comment]
Thanks for the input, just deployed it with commit 72b7c0ab8bf8edb5fa5f46cfdca3aeeee325e23d
