### ISSUE TITLE
Problem in running the app

### ISSUE THREAD

**Issue by rnehra01** [JacobReynolds/ssrfDetector#9]
It would be nice if guidelines to run the app locally are given.

**Comment by JacobReynolds** [comment]
I will work on getting the documentation written up.

**Comment by rnehra01** [comment]
It would be great if you could provide basic steps to set up this for now.

**Comment by JacobReynolds** [comment]
The code has been updated to run locally.  The blinkie server is dependent on hostnames though, so if it is running on port 3001 (as default) `http://localhost:3001` will not work.  An entry needs to be added into the /etc/hosts file for `127.0.0.1 a.blinkie.xyz` and then you'll need to register 'a' as your domain on the Detector app.  

It's kind of a pain, but it becomes easier if you set it up with an actual domain name and configure Nginx to take care of it all.  Hopefully this will work for you.

-Jake
